version: "3.8"

services:
  api:
    build: ./server
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
