version: "3.8"

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: golang-api-api:latest
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: golang-api-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - api
