global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "my_go_app"
    static_configs:
      - targets: ["host.docker.internal:2112"]
