name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Set working directory environment variable
        run: echo "WORKING_DIR=$(pwd)/server" >> $GITHUB_ENV

      - name: Install Go dependencies
        run: go mod tidy
        working-directory: ${{ env.WORKING_DIR }}

      - name: Set AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: echo "AWS credentials set"

      - name: Run Go tests
        run: go test -v ./...
        working-directory: ${{ env.WORKING_DIR }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./client

      - name: Build frontend
        run: npm run build
        working-directory: ./client

      - name: Log in to Docker Hub
        run: echo "${{ secrets.PASSWORD }}" | docker login ${{ secrets.REGISTRY }} -u ${{ secrets.USERNAME }} --password-stdin

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker tag golang-api-api:latest ${{ secrets.USERNAME }}/golang-api-api:latest
          docker tag golang-api-frontend:latest ${{ secrets.USERNAME }}/golang-api-frontend:latest
          docker push ${{ secrets.USERNAME }}/golang-api-api:latest
          docker push ${{ secrets.USERNAME }}/golang-api-frontend:latest
